/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Ciclista;
import modelo.ServiciosCiclista;

/**
 *
 * @author William Duarte
 */
public class GUIListarCiclista extends javax.swing.JFrame implements IActualizableCiclista{

    /**
     * Creates new form GUIListarCiclista
     */
    private ServiciosCiclista ser;
    DefaultTableModel modelo;
    
    public GUIListarCiclista(ServiciosCiclista refSer) {
        initComponents();
        ser = refSer;
        modelo = new DefaultTableModel();
        modelo.addColumn("NUMERO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("EQUIPO");
        this.jTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar");
        setPreferredSize(new java.awt.Dimension(350, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LISTADO DE CICLISTAS INSCRITOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(450, 250));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, 300, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/list1.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(350, 250));
        jLabel1.setMinimumSize(new java.awt.Dimension(350, 250));
        jLabel1.setPreferredSize(new java.awt.Dimension(350, 250));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void cambio() {
        listar();
    }
    
    public void listar()
    {
        while (modelo.getRowCount() > 0) 
        {
        modelo.removeRow(0);
        }
        
        ArrayList<Ciclista> x = ser.darCiclistas();
        String []datos = new String[3];

        for (int i = 0; i < x.size(); i++) {
            Ciclista ci = x.get(i);
            datos[0] = Integer.toString(ci.getNumero());
            datos[1] = ci.getNombre();
            datos[2] = ci.getEquipo();
            
            modelo.addRow(datos);
        }
    }
}
